name: Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version: [27.1, 28.2, 29.4]
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - name: Run tests
        run: emacs --batch -L . -l test.el -f ert-run-tests-batch-and-exit
